joint_position_controller:
    type: franka_controllers/PandaJointPositionController
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    publish_rate: 30.0

joint_controller_torque_input:
    type: franka_controllers/PandaJointControllerTorqueInput
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    kp: 16.0
    kd: 8.0
    publish_rate: 30.0
    displacement:
        - 0.1
        - 0.1
        - 0.1
        - 0.1
        - 0.2
        - 0.1
        - 0.1

test_controller:
    type: franka_controllers/TestController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    publish_rate: 50.0

    kp: 0.1
    kd: 0.0

impedance_force_controller:
    type: franka_controllers/ImpedanceForceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    k_gains:
        - 400.0
        - 400.0
        - 400.0
        - 20.0
        - 20.0
        - 20.0

    k_collision: 50.0

state_controller:
    type: franka_controllers/PandaStateController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    publish_rate: 30.0

joint_velocity_controller:
    type: franka_controllers/PandaJointVelocityController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    publish_rate: 50.0
    kp: 400.0
    kd: 40.0

cartesian_velocity_controller:
    type: franka_controllers/PandaCartesianVelocityController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    publish_rate: 50.0
    k_gains:
        - 200.0
        - 200.0
        - 200.0
        - 200.0
        - 200.0
        - 200.0
        - 200.0

force_controller:
    type: franka_controllers/PandaForceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    publish_rate: 100.0

hybrid_force_controller:
    type: franka_controllers/HybridForceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

    publish_rate: 100.0
